### PR TITLE
Build tool and docs

### PR DESCRIPTION
**Pull request by JJ**
It took me a good while to figure out why nothing in the docs was working, so I finally write this helper Makefile and modified docs a bit. It also refs #14 , which gave me the hint.

### CODE REVIEW

**Comment by bluebird75** [comment]
Hi JJ !

Thanks for the contribution. 

However, I already have a central python files responsbile for managing mostly everything ( doit.py ). I prefer you to add an install target to that file rather than a new file and tool to maintain.

It should not be that difficult, your Makefile is super simple. Don't hesitate to ask for support if needed, I promise I will take less than 2 months to answer this time...

Cheers,

Philippe

**Comment by JJ** [comment]
Will try to. Not as good with Python, we oldtimers actually prefer Makefiles :-)

**Comment by JJ** [comment]
Here you go. Will you keep maintaining the Windows version? The build fails.

**Comment by bluebird75** [comment]
Good !

**Pull request merged**
