### PR TITLE
My changes for v3.2 release

### PR DESCRIPTION
**Pull request by n1tehawk**
Related to #44 - These are the patches I'd like you to consider for merging.

Regards, NiteHawk

### CODE REVIEW

**Comment by bluebird75** [comment]
Nice for the addStatus, I also had that in mind at some point.

For the io.write vs io.stdout:write, would you care to elaborate on the difference for a Lua newbie like me ?

**Comment by n1tehawk** [comment]
> For the io.write vs io.stdout:write, would you care to elaborate on the difference for a Lua newbie like me ?

There is none - except that `io.write()` is shorter. See e.g. http://www.lua.org/manual/5.1/manual.html#pdf-io.write

**Comment by bluebird75** [comment]
I prefer that explicit form then. That's my python background where "explicit is better than implicit" is a key value....

**Comment by n1tehawk** [comment]
Okay. To straighten this out now, I'll close this PR and create another one - with 2016fc6 and 3cd17f0 rebased on top of current master.

Regards, NiteHawk

**Pull request closed without merging**
