### PR TITLE
use black to pass flake8 for py file

### PR DESCRIPTION
**Pull request by waketzheng**
Use `black` to  reformat python file
```
pip install --user toml black flake8
black doit.py
```

### CODE REVIEW

**Comment by bluebird75** [comment]
Thanks for the contribution.

Can you remove the pyproject file ? I don't see the interest here

**Comment by waketzheng** [comment]
Nice. I use `.flake8` to replace pyproject file, and `flake8` complaint nothing now.

**Comment by bluebird75** [comment]
I don't want to introduce new files. There are already too many files at the root of this project. So, can we have it without the .flake8 file ?

**Comment by waketzheng** [comment]
Sure~
And you can run the following command at the root of this project. So that `flake8` will pass next time.
```bash
echo -e '[flake8]\nmax-line-length=150\nextend-ignore=E401\nexclude=doc/' > .flake8 && echo .flake8 >> .git/info/exclude
```

**Pull request closed without merging**
