### PR TITLE
Determine access to undefined variables by static analysis

### PR DESCRIPTION
**Pull request by n1tehawk**
This picks up a suggestion from #53 to have some automated checks for missing `local` keywords (introducing unwanted "globals").

The first patch in the series introduces a basic framework for that and the _run_static_checks.lua_ script. The remaining ones deal with cleanup of the current code base.

### CODE REVIEW

**Comment by n1tehawk** [comment]
See e.g. https://travis-ci.org/bluebird75/luaunit/jobs/135825153 for a "live" result of these checks.

**Comment by linuxmaniac** [comment]
why don't you use https://github.com/mpeterv/luacheck for the static analysis?

**Comment by n1tehawk** [comment]
Hi linuxmaniac!

>why don't you use https://github.com/mpeterv/luacheck for the static analysis?

There is a slight problem with the more 'conventional' approaches and existing tools: _LuaUnit_ (and its checks) works with some assumptions that violate strict checking for undefined variables. For example, tests / test suites are expected to be defined as "globals" following a certain naming convention.

That means we would likely have to customize any checker to allow for "expected" globals. The bytecode analysis seemed straightforward and simple enough to implement, so in the end I just decided to do it on my own, integrating rather 'seamlessly' with the existing code base. It also works across all supported Lua versions (which is something I'm not certain that all existing solutions would do).

Regards, NiteHawk

**Comment by mpeterv** [comment]
Hi @n1tehawk,

> That means we would likely have to customize any checker to allow for "expected" globals. The bytecode analysis seemed straightforward and simple enough to implement, so in the end I just decided to do it on my own, integrating rather 'seamlessly' with the existing code base. 

Configuring luacheck to allow some globals is also fairly straightforward. Put this into `.luacheckrc` file in the root of your project:

```lua
only = {"1"}
std = "max"
exclude_files = {"doc"}

files = {
   ["luaunit.lua"] = {ignore = {"LuaUnit", "EXPORT_ASSERT_TO_GLOBALS"}},
   ["example_with_luaunit.lua"] = {ignore = {"LuaUnit", "EXPORT_ASSERT_TO_GLOBALS", "[Tt]est[%w_]+",
      "assertEquals", "assertNotEquals", "assertTrue", "assertFalse"}},
   ["run_functional_tests.lua"] = {ignore = {"test%w+"}},
   ["test/compat_luaunit_v2x.lua"] = {ignore = {"EXPORT_ASSERT_TO_GLOBALS", "[Tt]est[%w_]+",
      "assert%w+"}},
   ["test/legacy_example_with_luaunit.lua"] = {ignore = {"LuaUnit", "EXPORT_ASSERT_TO_GLOBALS",
      "[Tt]est[%w_]+", "assertEquals", "assertNotEquals", "assertTrue", "assertFalse"}},
   ["test/test_luaunit.lua"] = {ignore = {"TestMock", "TestLuaUnit%a+", "MyTest%w+"}},
   ["test/test_with_err_fail_pass.lua"] = {ignore = {"[Tt]est[%w_]+"}},
   ["test/test_with_xml.lua"] = {ignore = {"Test%w+"}}
}

```

This mirrors `files_and_exceptions` table from your `run_static_tests.lua` file. The first two lines allow standard globals from all Lua versions and disable checks not related to globals. To run it use `luacheck .`.

> It also works across all supported Lua versions (which is something I'm not certain that all existing solutions would do).

Luacheck supports all Lua versions.

**Comment by n1tehawk** [comment]
Hi Peter, and thanks for having a look into this!

That's actually pretty cool. And since I'd prefer not to reinvent the wheel on this one, I'll definitely give _Luacheck_ a try. :smile:

**Comment by mpeterv** [comment]
@n1tehawk no problem! BTW, it seems that luaunit CI setup for travis installs luarocks, so you can just do `luarocks install luacheck` to get luacheck. For Appveyor, and if you want to get rid of these `.travis` and `.appveyor` folders, check out [hererocks](https://github.com/mpeterv/hererocks#using-hererocks-to-set-up-automated-testing) (so many shameless plugs...)

**Comment by n1tehawk** [comment]
@mpeterv I'm observing segfaults with _Luacheck_ and _LuaJIT 2.1.0-beta2_, e.g. https://travis-ci.org/n1tehawk/luaunit/jobs/135944298 or https://travis-ci.org/n1tehawk/luaunit/jobs/135953635. I'll have to see when I find time to try narrowing them down further. They're a bit hard to trace, since they seem intermittent(?) and I have no easy way of reproducing them locally...

**Comment by mpeterv** [comment]
@n1tehawk looks like a LuaJIT bug, although it's not in 2.1.0-beta2 but in HEAD of LuaJIT v2.1 branch that travis uses. Switching to 2.1.0-beta2 should fix it. I can reproduce it fairly reliably, I'll bisect and report it.

**Comment by n1tehawk** [comment]
Yes, I should have been more precise - of course that's the current HEAD of the 2.1 branch. If you're already aware of it, it's fine. The LuaUnit checks aren't affected by this on a larger scale, as we allow the very latest LuaJIT versions to fail anyway (for whatever reason) without breaking the build.

Regards, NiteHawk

**Comment by n1tehawk** [comment]
Luacheck seems to work very well, and I've decided to switch the analysis over to it. Thus pull request #55 supersedes this one, and I'll be closing it.

**Pull request closed without merging**
