### PR TITLE
Added custom assert messages

### PR DESCRIPTION
**Pull request by icamys**
Implemented feature mentioned in #97. Additional tests needed. I will add them if the PR will be accepted in future by repo owner

### CODE REVIEW

**Comment by icamys** [comment]
Added all necessary tests. Please check the PR. I will be glad to listen to your comments.

**Comment by bluebird75** [comment]
First of all, thanks for your effort on this, it is always appreciated when contributions are proposed.

I am going to accept the general contributions, after some adjustements : 

1. Please remove the removal of spaces at the end of lines. It is a small cosmetic improvement which makes your patch more tedious to read. If those spaces bother you, please submit another PR dedicated to cosmetic improvements.

2. I don't like the fact that the same code is repeated over and over to include the optional message. You can certainly craft a function to take care of this and have a smaller patch, with less copy/paste.

Apart from that, it's great that you also updated the tests, and espcially have added some missing tests.

Cheers,

Philippe

**Comment by icamys** [comment]
@bluebird75 Hi, Phillip! Thanks for your fair remarks. I've updated my commit taking into account your requests.

**Comment by juodumas** [comment]
Asserting in a loop (for example a parsing function) is impossible without this change. Please consider merging this for 3.3.

**Comment by bluebird75** [comment]
I did a reimplementation around March 4. See 3d17658eff11a733d31e388e4f80265114212741 

This is now fully supported and documented and integrated into v3.3

**Pull request closed without merging**
